export const data = [
  {
    id: 1,
    image: "/images/get-linked.png",
    title: "Getlinked",
    github: "https://github.com/igbanibo-Dengi/get_linked",
    demo: "https://get-linked-amber.vercel.app/",
    icons: ["React", "Tailwind CSS", "Framer Motion"],
    description: "React, Tailwind CSS, and Framer Motion.",
  },
  {
    id: 2,
    image: "/images/get-linked.png",
    title: "PixelHost",
    github: "https://github.com/igbanibo-Dengi/vision",
    demo: "https://pixelhost-three.vercel.app/",
    icons: ["React", "Tailwind CSS", "Framer Motion"],
    description: "Built with Next.js, Tailwind CSS, and Framer.",
  },
  {
    id: 3,
    image: "/images/get-linked.png",
    title: "MCU",
    github: "https://github.com/igbanibo-Dengi/mcu-database",
    demo: "https://marvelcinematicuniversedatabase.netlify.app/",
    icons: ["React", "Tailwind CSS", "HTML"],
    description: "React, Tailwind CSS, and HTML.",
  },
  {
    id: 4,
    image: "/images/get-linked.png",
    title: "Dipps Beautifyers",
    github: "https://github.com/igbanibo-Dengi/dipps-",
    demo: "https://dipps.netlify.app/",
    icons: ["React", "Tailwind CSS", "HTML", "Framer Motion"],
    description:
      "React, Tailwind CSS, HTML, and Framer Motion for delightful animations.",
  },
  {
    id: 5,
    image: "/images/get-linked.png",
    title: "Nexus Gaming",
    github: "https://github.com/igbanibo-Dengi/nexus-gaming",
    demo: "https://nexusgaming.netlify.app/",
    icons: ["Bootstrap", "HTML", "CSS", "JavaScript"],
    description: "Bootstrap, HTML, CSS, and JavaScript.",
  },
];
